'use client';
import {useEffect,useRef,useState} from 'react';
import {projects} from './projects';
import {ProjectActions,SafraSlides} from './project-actions';
const sections=[['inicio','Início'],...projects.map(p=>[p.id,p.name]),['grade','Grade de projetos'],['contatos','Contatos']];
function Picture({name,alt,className='',eager=false}:{name:string;alt:string;className?:string;eager?:boolean}){return <img className={className} src={`./assets/${name}.webp`} alt={alt} loading={eager?'eager':'lazy'} decoding="async"/>}
function Shot({name,alt,className='',href}:{name:string;alt:string;className?:string;href?:string}){return href?<a className={`shot ${className}`} href={href}><Picture name={name} alt={alt} eager/><span className="shot-label">{alt}</span></a>:<figure className={`shot ${className}`}><Picture name={name} alt={alt}/><figcaption>{alt}</figcaption></figure>}
function Copy({index}:{index:number}){const p=projects[index];const details=<><h3>{p.headline}</h3><p>{p.description}</p><p className="role">{p.role}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><ProjectActions id={p.id} name={p.name}/></>;return <div className="project-copy reveal"><p className="eyebrow">{p.number} / {p.category}</p><h2>{p.name}<span>{p.client}</span></h2>{p.id==='bim'&&<div className="bim-cover"><Shot name="bim-slide-1" alt="BIM Mobile — capa da apresentação"/></div>}{p.id==='alui'&&<div className="alui-cover"><Shot name="alui-slide-1" alt="Alui — o celular como aliado do aprendizado"/></div>}{(p.id==='alui'||p.id==='bim')?<div className={`${p.id}-details`}>{details}</div>:details}</div>}
export default function Home(){const [active,setActive]=useState('inicio');const [scrolled,setScrolled]=useState(false);const hero=useRef<HTMLElement>(null);
useEffect(()=>{let raf=0;const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;const update=()=>{setScrolled(window.scrollY>90);let current='inicio';for(const [id] of sections){const e=document.getElementById(id);if(e&&e.getBoundingClientRect().top<window.innerHeight*.45)current=id;}setActive(current);if(!reduced)document.querySelectorAll<HTMLElement>('.parallax').forEach(el=>{const rect=el.getBoundingClientRect();const delta=Math.max(-20,Math.min(20,(window.innerHeight/2-rect.top)*.035));el.style.setProperty('--scroll',`${delta}px`);});raf=0;};const scroll=()=>{if(!raf)raf=requestAnimationFrame(update)};update();window.addEventListener('scroll',scroll,{passive:true});const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>io.observe(e));return()=>{window.removeEventListener('scroll',scroll);cancelAnimationFrame(raf);io.disconnect()};},[]);
return <><a className="skip" href="#safra">Pular para os projetos</a>
<nav className={`floating-nav ${scrolled?'scrolled':''}`} aria-label="Navegação principal">{[['safra','Ver projetos'],['grade','Grade de projetos'],['contatos','Contatos']].map(([id,label])=><a key={id} href={`#${id}`} className={active===id||(id==='safra'&&['reuse','alui','bim'].includes(active))?'selected':''} aria-current={active===id?'location':undefined}>{label}</a>)}</nav>
<nav className="progress" aria-label="Progresso da página">{sections.map(([id,label])=><a key={id} href={`#${id}`} aria-label={label} aria-current={active===id?'location':undefined} className={active===id?'active':''}><span>{label}</span><i/></a>)}</nav>
<main><section id="inicio" ref={hero} className="hero" onPointerMove={e=>{if(e.pointerType==='mouse'&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches){const r=e.currentTarget.getBoundingClientRect();hero.current?.style.setProperty('--mx',`${(e.clientX/r.width-.5)*16}px`);hero.current?.style.setProperty('--my',`${(e.clientY/r.height-.5)*12}px`)}}} onPointerLeave={()=>{hero.current?.style.setProperty('--mx','0px');hero.current?.style.setProperty('--my','0px')}}>
<div className="hero-orbit"><Shot name="alui-3" alt="Conheça a Alui" className="hero-a phone" href="#alui"/><Shot name="safra-screen" alt="Conheça o Safra" className="hero-b" href="#safra"/><Shot name="reuse-web" alt="Conheça o ReUse" className="hero-c" href="#reuse"/><Shot name="bim-model" alt="Conheça o BIM Mobile" className="hero-d" href="#bim"/></div>
<div className="hero-copy"><Picture name="alan" alt="Alan Mateus" className="portrait" eager/><h1>Alan<br/><span>Mateus</span><b>.</b></h1><p className="intro">Transformando curiosidade<br/>em experiências digitais.</p><p className="bio">Estudante de ADS na Unifor. Exploro desenvolvimento de software, UI/UX e inovação — dos hackathons aos projetos reais.</p></div>
</section>
<div className="section-divider"><span>TRABALHOS SELECIONADOS</span><span>2026</span></div>
<section id="safra" className="project safra"><Copy index={0}/><div className="safra-main reveal parallax"><Shot name="safra-screen" alt="Safra — visualização por plataforma"/><span className="image-note">Interface apresentada no desafio de inovação</span></div><SafraSlides/></section>
<section id="reuse" className="project reuse"><div className="reuse-phones reveal parallax"><Shot name="reuse-home-crop" alt="ReUse — início em modo escuro" className="phone phone-one"/><Shot name="reuse-detail-crop" alt="ReUse — detalhes de um anúncio" className="phone phone-two"/><Shot name="reuse-third-crop" alt="ReUse — início em modo claro" className="phone phone-three"/></div><Copy index={1}/><div className="reuse-web reveal"><Shot name="reuse-web" alt="ReUse — apresentação da plataforma"/></div></section>
<section id="alui" className="project alui"><Copy index={2}/><div className="alui-stage reveal">{[{n:2,label:'boas-vindas'},{n:3,label:'próximas aulas'},{n:4,label:'ofensiva e metas'},{n:18,label:'questão de múltipla escolha'},{n:15,label:'métricas de aprendizado'}].map((screen,i)=><Shot key={screen.n} name={screen.n===15?'alui-metrics-crop':`alui-${screen.n}`} alt={`Alui — ${screen.label}`} className={`phone orbit-screen orbit-${i+1}`}/>)}</div></section>
<section id="bim" className="project bim"><div className="bim-title"><Copy index={3}/></div><div className="bim-images reveal parallax"><Shot name="bim-model" alt="BIM Mobile — modelos e informações da obra"/><Shot name="bim-plan" alt="BIM Mobile — planejamento e acompanhamento"/></div></section>
<section id="grade" className="project-grid"><div className="grid-heading reveal"><p className="eyebrow">UM OUTRO JEITO DE EXPLORAR</p><h2>Todos os projetos<span>.</span></h2><p>Quatro ideias. Diferentes formas de resolver problemas.</p></div><div className="cards">{projects.map(p=><article key={p.id} className={`project-card card-${p.id} reveal`}><a href={`#${p.id}`} className="card-image" aria-label={`Ver projeto ${p.name}`}><Picture name={p.image} alt={`Prévia de ${p.name}`}/></a><div className="card-content"><span className="eyebrow">{p.category}</span><h3>{p.name}</h3><p>{p.summary}</p><a className="project-link" href={`#${p.id}`}>Ver projeto</a></div></article>)}</div></section>
<section id="contatos" className="contact"><div className="contact-photo reveal"><Picture name="alan" alt="Retrato de Alan Mateus"/><span>FORTALEZA, CE</span></div><div className="contact-copy reveal"><p className="eyebrow">BOAS IDEIAS COMEÇAM COM UMA CONVERSA</p><h2>Vamos criar<br/>algo juntos<span>?</span></h2><div className="contact-links"><a href="mailto:alanmateusqueiroz@gmail.com">Email</a><a href="https://linkedin.com/in/alanmateusqueiroz" target="_blank" rel="noopener noreferrer">LinkedIn</a><a href="https://github.com/alanmateuz" target="_blank" rel="noopener noreferrer">GitHub</a></div><p>Sou Alan Mateus, técnico em Edificações pelo IFCE e estudante de Análise e Desenvolvimento de Sistemas na Unifor. Gosto de conectar pessoas, design e tecnologia para tirar ideias do papel.</p></div></section></main><footer><a className="wordmark" href="#inicio">am<span>.</span></a><span>Alan Mateus · 2026</span><a href="#inicio">Voltar ao início</a></footer></>}
